apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-store
  labels:
    app: f1-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-store-api
  template:
    metadata:
      labels:
        app: f1-store-api
    spec:
      containers:
        - name: f1-store-api
          image: 010526250323.dkr.ecr.us-east-1.amazonaws.com/f1-store-api/0960434b7b3baf0277ba040ad9246c58580a24ca
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: f1-store-api-service
spec:
  selector:
    app: f1-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
