apiVersion: apps/v1
kind: Deployment
metadata:
  name: f1-store
  labels:
    app: f1-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f1-store-api
  template:
    metadata:
      labels:
        app: f1-store-api
    spec:
      containers:
        - name: f1-store-api
          image: 010526250323.dkr.ecr.us-east-1.amazonaws.com/f1-store-api/0960434b7b3baf0277ba040ad9246c58580a24ca
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: f1-store-api-service
spec:
  selector:
    app: f1-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: f1-store-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
#    external-dns.alpha.kubernetes.io/hostname: a84aa51d6ec9a4f48bd22ece7e88d152-1755934926.us-east-1.elb.amazonaws.com
#    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:898730021473:certificate/35216157-601a-49c9-9c27-9d297c0962e6
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /api
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: f1-store-api-service
                port:
                  number: 80
